version: "3"

services:
  nginx:
    image: nginx:stable
    container_name: ringnginx1
    #ports:
    #  - "8000:8000"
    environment:
      - VIRTUAL_HOST=mydev.ring.development.com
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./ring/static:/static
    depends_on:
      - python

  python:
    build: ./python
    container_name: ringpython1
    command: uwsgi --socket :8001 --module ring.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      #- ./src:/code
      - ./ring:/code
      - ./static:/static
    expose:
      - "8001"

networks:
  default:
    external:
      name: mydev
